version: '3.8'

services:
  # Backend API Service (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - DEBUG=true
      - RELOAD=true
    volumes:
      - ./backend:/app
      - ./ml:/app/ml
      - backend_uploads:/app/uploads
    depends_on:
      - redis
    networks:
      - flashfit-network
    restart: unless-stopped
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Service (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - flashfit-network
    restart: unless-stopped
    stdin_open: true
    tty: true

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - flashfit-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Redis Commander (Redis GUI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - flashfit-network
    profiles:
      - tools

volumes:
  redis_data:
  backend_uploads:

networks:
  flashfit-network:
    driver: bridge