global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@flashfit.ai'
  smtp_auth_username: 'alerts@flashfit.ai'
  smtp_auth_password: 'your_email_password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
    send_resolved: true

- name: 'critical-alerts'
  email_configs:
  - to: 'admin@flashfit.ai'
    html: |
      <h2>[CRITICAL] FlashFit AI Alert: {{ .GroupLabels.alertname }}</h2>
      {{ range .Alerts }}
      <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
      <p><strong>Description:</strong> {{ .Annotations.description }}</p>
      <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
      <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
      <hr>
      {{ end }}
  webhook_configs:
  - url: 'http://127.0.0.1:5001/critical'
    send_resolved: true

- name: 'warning-alerts'
  email_configs:
  - to: 'team@flashfit.ai'
    html: |
      <h2>[WARNING] FlashFit AI Alert: {{ .GroupLabels.alertname }}</h2>
      {{ range .Alerts }}
      <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
      <p><strong>Description:</strong> {{ .Annotations.description }}</p>
      <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
      <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
      <hr>
      {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']